steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ["build","-t","$_AR_HOSTNAME/$_PROJECT_ID/cloud-run-source-deploy/$_IMAGE_NAME:$_SERVER",".","-f","Dockerfile","--cache-from","$_AR_HOSTNAME/$_PROJECT_ID/cloud-run-source-deploy/$_IMAGE_NAME:$_SERVER"]

# Push to the GCP AR registry 
- name: gcr.io/cloud-builders/docker
  args: ['push',"$_AR_HOSTNAME/$_PROJECT_ID/cloud-run-source-deploy/$_IMAGE_NAME:$_SERVER"]

options:
  logging: CLOUD_LOGGING_ONLY